### ISSUE TITLE
В github.io в примерах кода нет перевода на новую строку

### ISSUE THREAD

**Issue by pongo** [andrew--r/the-little-book-on-coffeescript#23]
В заголовке readme.md есть ссылка https://andrew--r.github.io/the-little-book-on-coffeescript

Если читать книгу по этой ссылке, то там в примерах кода нет перевода на новую строку - это очень плохо. Весь код всегда на одной строке показывается, хотя в оригинале не так.

Кроме того, в github.io нет никакого оформления, подсветки кода и т.д. - но это мелочи. А вот что нет перевода строк - это критично.

Пока не будет исправлен вариант на github.io, нужно убрать ссылку на него.

**Comment by andrew--r** [comment]
Спасибо за замечание.

Пока что нет времени заканчивать перевод, поэтому действительно уберу ссылку.
